// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WM.ControleEstoque.Infraestrutura.DB;

#nullable disable

namespace WM.ControleEstoque.Api.Migrations
{
    [DbContext(typeof(AplicacaoDbContexto))]
    [Migration("20231123192106_PrimeiroMigration")]
    partial class PrimeiroMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.CompraProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeCompra")
                        .HasColumnType("INT");

                    b.Property<decimal>("ValorCompraTotal")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("CompraProdutos");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Complemento")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(2)");

                    b.Property<int>("Numero")
                        .HasColumnType("INT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FornecedorNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("FornecedorTelefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(11)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(11)");

                    b.Property<DateTime>("Datacadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FuncionarioNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("FuncionarioSenha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<Guid>("LojaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.HasIndex("LojaId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(14)");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<decimal>("ProdutoValorUnitario")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.VendaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeVendida")
                        .HasColumnType("INT");

                    b.Property<decimal>("ValorVendaTotal")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.ToTable("VendaProdutos");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.CompraProduto", b =>
                {
                    b.HasOne("WM.ControleEstoque.Dominio.Entidades.Fornecedor", null)
                        .WithMany("CompraProdutos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Fornecedor", b =>
                {
                    b.HasOne("WM.ControleEstoque.Dominio.Entidades.Endereco", null)
                        .WithOne("Fornecedor")
                        .HasForeignKey("WM.ControleEstoque.Dominio.Entidades.Fornecedor", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Funcionario", b =>
                {
                    b.HasOne("WM.ControleEstoque.Dominio.Entidades.Endereco", null)
                        .WithOne("Funcionario")
                        .HasForeignKey("WM.ControleEstoque.Dominio.Entidades.Funcionario", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WM.ControleEstoque.Dominio.Entidades.Loja", null)
                        .WithMany("Funcionarios")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Loja", b =>
                {
                    b.HasOne("WM.ControleEstoque.Dominio.Entidades.Endereco", null)
                        .WithOne("Loja")
                        .HasForeignKey("WM.ControleEstoque.Dominio.Entidades.Loja", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Produto", b =>
                {
                    b.HasOne("WM.ControleEstoque.Dominio.Entidades.Categoria", null)
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WM.ControleEstoque.Dominio.Entidades.Fornecedor", null)
                        .WithMany("Produtos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Endereco", b =>
                {
                    b.Navigation("Fornecedor")
                        .IsRequired();

                    b.Navigation("Funcionario")
                        .IsRequired();

                    b.Navigation("Loja")
                        .IsRequired();
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Fornecedor", b =>
                {
                    b.Navigation("CompraProdutos");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("WM.ControleEstoque.Dominio.Entidades.Loja", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
